name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Install Flutter (latest stable)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3. Get dependencies
      - run: flutter pub get

      # 4. Clean previous builds
      - run: flutter clean

      # 5. Build APK or AppBundle
      - run: flutter build apk --release
      # Or for Play Store:
      # - run: flutter build appbundle --release

      # 6. Upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
