name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # latest stable Flutter version

      # 3. Get dependencies
      - run: flutter pub get

      # 4. Clean previous builds
      - run: flutter clean

      # 5. Build APK
      - run: flutter build apk --release

      # 6. Upload APK as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
