name: Build Flutter APK

# Trigger the workflow on push to main branch, pull requests, or manual trigger

on:
push:
branches: [ main ]
pull_request:    
 branches: [ main ]
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
# Checkout the code
- name: Checkout repository
uses: actions/checkout@v4

# Setup Java JDK
- name: Setup Java JDK
uses: actions/setup-java@v4
with:
distribution: 'temurin'
java-version: '17'

# Setup Flutter
- name: Setup Flutter
uses: subosito/flutter-action@v2
with:
flutter-version: '3.16.0'
channel: 'stable'

# Get Flutter dependencies
- name: Install dependencies
run: flutter pub get

# Run tests (optional)
- name: Run tests
run: flutter test

# Build APK
- name: Build APK
run: flutter build apk --release

# Upload APK as artifact
- name: Upload APK
uses: actions/upload-artifact@v4
with:
name: calculator-app-release
path: build/app/outputs/flutter-apk/app-release.apk
```
